[build]
  publish = "web-build"
  command = "npm run build:web"

[build.environment]
  NODE_VERSION = "18"
  # Database will be available via environment variables
  # Set DATABASE_URL in Netlify dashboard > Site settings > Environment variables

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*" 